name: ts_design_core
description: design ui kit
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  cloud_firestore: ^4.4.0
  cloud_firestore_platform_interface: ^5.11.0
  cloud_firestore_web: ^3.3.0
  equatable: ^2.0.3
  firebase_analytics: ^10.1.1
  firebase_analytics_web: ^0.5.1+9
  firebase_auth: ^4.2.6
  firebase_auth_platform_interface: ^6.11.8
  firebase_auth_web: ^5.2.5
  firebase_core: ^2.5.0
  firebase_core_web: ^2.1.1
  firebase_ui_auth: ^1.1.11
  firebase_ui_firestore: ^1.2.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_portal: ^1.1.3
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  google_fonts: ^3.0.1
  life_hooks: ^0.0.18
  sliver_tools: ^0.2.5
  tap_builder: ^0.3.4

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  xsoulspace_lints: ^0.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# assets:
#   - assets/images/
# To add assets to your application, add an assets section, like this:
# assets:
#   - google_fonts/
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# fonts:
#   - family: la_icons
#     fonts:
#       - asset: packages/la_design_core/fonts/la_icons.ttf
